[package]
name = "diskann-wide"
version.workspace = true
description.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
edition = "2024"

[lints]
clippy.undocumented_unsafe_blocks = "warn"
clippy.uninlined_format_args = "allow"

[dev-dependencies]
paste.workspace = true
rand.workspace = true
half = { workspace = true, features = ["rand_distr", "num-traits"] }

[dependencies]
cfg-if.workspace = true
half.workspace = true
